name: my_counter_app
description: The application reminds about keeping a good posture.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: 0.15.0
  screen: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "0.8.0"

flutter_icons:
  android: true
  image_path: "assets/icon.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/sound.wav